pipeline {
    agent any
    stages {
        stage('build infrastructure') {
            steps {
                withAWS(credentials: 'aws', region: 'eu-west-1') {
                    dir("terraform") { 
                        sh 'terraform init -reconfigure'
                        sh 'terraform destroy --var-file dev.tfvars -auto-approve'
                    }
                }
            }
        }
    }
}
